### ISSUE TITLE
Test Failure:  test_create_single_detailed_forest

### ISSUE THREAD

**Issue by twcook** [paul-hoehne/MarkLogic_Python#10]
Executing: 

    python -m unittest tests/databases/test_database.py 

Traceback:

```
======================================================================
ERROR: test_create_single_detailed_forest (tests.databases.test_database.TestDatabase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tim/S3Model/MarkLogic_Python/tests/databases/test_database.py", line 127, in test_create_single_detailed_forest
    db.create(conn)
  File "/home/tim/S3Model/MarkLogic_Python/marklogic/models/database.py", line 1438, in create
    raise UnexpectedManagementAPIResponse(response.text)
marklogic.models.utilities.exceptions.UnexpectedManagementAPIResponse: {"errorResponse":{"statusCode":"400", "status":"Bad Request", "messageCode":"MANAGE-CONFLICTINGCONFIG", "message":"MANAGE-CONFLICTINGCONFIG: (err:FOER0000) A conflict has been detected:  database forest configurations differ."}}

----------------------------------------------------------------------
Ran 5 tests in 362.116s

FAILED (errors=1)
```
*Using ML 8.0-1.1 (developer)
*Python 3.4

It leaves a forest (detailed-forest-create-forest1) in the mount error state.
The database (detailed-forest-create-test-db) is left in the available state. 

Any ideas?

**Comment by paul-hoehne** [comment]
The error suggests that the forest was created but it already existed.  You can use the management console (port 8001) to remove the forest and databases manually.

**Comment by twcook** [comment]
I forgot to mention that I had used the Admin UI to delete the forest and
the database.
In fact, I retried this a few times. I reloaded the UI to be sure they were
actually deleted.

Any tips on testing/verifying where the error is located?

Thanks.


On Fri, Apr 3, 2015 at 5:03 PM, Paul Hoehne <notifications@github.com>
wrote:

> The error suggests that the forest was created but it already existed. You
> can use the management console (port 8001) to remove the forest and
> databases manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paul-hoehne/MarkLogic_Python/issues/10#issuecomment-89407242>
> .
>



-- 

============================================
Timothy Cook
LinkedIn Profile:http://www.linkedin.com/in/timothywaynecook
MLHIM http://www.mlhim.org

**Comment by paul-hoehne** [comment]
I'm on client site right now, but in about an hour and a half I'll be able to sit down and take a detailed look at it.  I've been testing with Python 2.7.  I really need to also try 3.4.

**Comment by twcook** [comment]
Thanks.  This doesn't look like a 2.7 vs. 3.4 problem.  I wonder if it has something to do with my dev machine not being on the same localhost as ML?  Are the forest names returned differently? PRobably not, doesn't make sense since it is over REST anyway.

**Comment by paul-hoehne** [comment]
I actually use a VM to run ML when I run tests.  But I'll be able to take a look at it in a few minutes.

**Comment by paul-hoehne** [comment]
Okay, I double checked all the tests and added "main" methods to the tests.  I ran them individually.  I also fixed an issue with the Field test.  Are you running them individually?

**Comment by twcook** [comment]
Yes, I was just running the test_database.py

**Comment by twcook** [comment]
I tried a few other things including a python 2.7  I 'think' it is a path problem on the Windows install.  But it is late here (UTC-3) so I will look at it again in the morning.  Cheers.

**Comment by paul-hoehne** [comment]
Hmm... I just realized I was running 8.0-1.  I just upgraded to 8.0-1.1 and re-ran the tests.  What OS is your ML instance running on?  I'm running Cent OS 7.

**Comment by twcook** [comment]
Windows 8.1

**Comment by twcook** [comment]
SOLVED: sort of.  The actual error in the Admin UI is:

´´´
XDMP-FORESTERR: Error in initialization of forest-detailed forest-create-forest1: SVC-DIRCREAT: Directory creation error: CreateDirectory '/ data / large / Forests': The system can not find the path specified.
´´´
So, I created a Forest manually and I cannot set those directories in the Admin UI either.  Is this a limitation of the developer license version or a bug in 8.0-1.1?  

If I set the directory values in test_settings.py to an empty string, the database tests pass.

**Comment by twcook** [comment]
Correction: I CAN edit the data directory, large directory and fast directory entries, in the Admin UI now. Also, the test_database.py passes after changing the settings back to  

    large_data_directory = "/data/large"
    fast_data_directory = "/data/fast"

So 'something' was weird with that Windows installation.  

I really wish ML supported Ubuntu. 

I have successfully  used alien to convert the ML rpm to deb and installed it on Ubuntu.  I think I'll do that again and quit using Windows. :-)

**Comment by paul-hoehne** [comment]
Did you look in test_settings.py?  That's where I set the paths for the large data directory and fast data directory options.  Otherwise, I leave the default setting for the forest which something like C:\Program Files\MarkLogic\Data on Windows.

**Comment by twcook** [comment]
It wasn't clear to me that the directories had to exist already (or a symbolic link?) for this to work. 
MarkLogic doesn't automatically create them.  

I added some text to test_settings.py to clarify the situation in case someone else has this issue.

**Comment by paul-hoehne** [comment]
Cool.

**Comment by twcook** [comment]
Okay, I'll do that with the next commit.
