### ISSUE TITLE
Re-organize directory structure to work well with setuptools

### ISSUE THREAD

**Issue by rmchamberlain** [paul-hoehne/MarkLogic_Python#2]
Do you have plans to do this in the near future to allow easy installation and development via pip and easy_install?  I'm referring to the typical Python package structure:

docs/
examples/
tests/
marklogic/
&nbsp;&nbsp;&nbsp;&nbsp;models/
&nbsp;&nbsp;&nbsp;&nbsp;etc...
setup.py
README.md
etc....

If so, I'd be happy to work it up in a PR.  If not, no worries, I just wanted to know before I start using the code.

**Comment by paul-hoehne** [comment]
Yes, in the next push or two.

**Comment by paul-hoehne** [comment]
It should install using easy install, but I've only tried it with Python 3.4 and using a virtual environments.

**Comment by rmchamberlain** [comment]
Thanks!  So far it's working for me at the system level with Python 2.7 using `python setup.py develop`
