### ISSUE TITLE
Trello board

### ISSUE THREAD

**Issue by paul-hoehne** [paul-hoehne/MarkLogic_Python#22]
I've been playing with Trello, let me know if this is a good way to track new features.

https://trello.com/b/pf8XPocu/marklogic-python

**Comment by glenfant** [comment]
IMHO Trello is a nice stuff, but you'd better use tags on issues in this tracker to get the same effect as Trello and avoid duplicate information.

**Comment by jmakeig** [comment]
> you'd [be] better [off using] tags on issues in this tracker to get the same effect as Trello and avoid duplicate information

Agreed.

**Comment by paul-hoehne** [comment]
Bye bye trello.
