### ISSUE TITLE
What version of requests do you have?

### ISSUE THREAD

**Issue by ndw** [paul-hoehne/MarkLogic_Python#23]
Hi,

I'm trying to get a simple test to work and I'm getting syntax errors of the form:

````
...
  File "/projects/github/MarkLogic_Python/marklogic/models/database.py", line 1436, in create
    response = requests.post(uri, json=self.config, auth=connection.auth)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
````

apparently because you're using `requests.post(uri, json=dict, ...)`.

That doesn't work for me, what I have to do is

````
requests.post(uri, data=json.dumps(dict), headers={"content-type": "application/json"}, ...)
````

I assume the issue is some incompatiblity with the requests library. Or something. I get the same problems with both Python 2.7 and Python 3.4.

**Comment by paul-hoehne** [comment]
It might be.  But the requests library should just do a json.dumps under the covers.  http://docs.python-requests.org/en/latest/api/   The dependency is on requests > 2.5.0.  What version of requests do you have?

**Comment by ndw** [comment]
My bad. All fixed.
