### ISSUE TITLE
FieldRange and field_range_index vs RangeField and range_field_index

### ISSUE THREAD

**Issue by ndw** [paul-hoehne/MarkLogic_Python#33]
I can see the appeal of FieldRange and field_range_index, but as the server calls them range_field_indexes, I'm tempted to swap them around.

**Comment by ndw** [comment]
But the admin UI has traditionally called them Field Range Indexes. Huh. Nevermind.

**Comment by ndw** [comment]
No. We don't get off that lucky. For most properties, the name of the getter/setter is taken directly from the name of the property:

````
self.config['enabled'] = "true"
````

lends itself to `self.enabled()` and `self.set_enabled()`. But for indexes, we end up with, for example:

````
self.config['range-element-index'] = [ {...}, {...} ]
````

that lends itself to `self.range_element_indexes()` which returns an array of `ElementRangeIndex` objects.

That inconsistency is bugging me. It seems like the method should be `element_range_indexes()` or the object should be `RangeElementIndex`.

Thoughts?

**Comment by paul-hoehne** [comment]
I vote for changing the accessor method.

**Comment by paul-hoehne** [comment]
But if you've got a stronger preference, I'd vote for that.

**Comment by ndw** [comment]
Ok. Coin flip really, as long as we agree they should match up. I've got all the indexes done. Working my way through the rest of the database guts.
