### ISSUE TITLE
Error in examples/simple_example.py

### ISSUE THREAD

**Issue by glenfant** [paul-hoehne/MarkLogic_Python#4]
Hi,

Running examples/simple_example.py yields a programming error :
```
Traceback (most recent call last):
  File "simple_example.py", line 14, in <module>
    db.create(conn).load_file(conn, "example_doc.json", "/test/document.json", ["example", "collection"])
  File "/Users/glenfant/projets/mlclient/MarkLogic_Python/marklogic/models/database.py", line 1409, in create
    if self.hostname is not None:
AttributeError: Database instance has no attribute 'hostname'
```
Mac OSX / Python 2.7.9

**Comment by paul-hoehne** [comment]
Hmmm… I’ll take a look when I get a chance.

Paul Hoehne
Senior Consultant
MarkLogic Corporation
paul.hoehne@marklogic.com
mobile: +1 571 830 4735
www.marklogic.com

Click http://po.st/hMGDFm to get your free NoSQL For Dummies e-book!

**Comment by glenfant** [comment]
Ah and ML 8.0 but it seems this error raised before connecting the server.

**Comment by paul-hoehne** [comment]
https://github.com/paul-hoehne/MarkLogic_Python/pull/5

**Comment by paul-hoehne** [comment]
Thanks!  I'll get to the code review comments when I get home.  I appreciate your taking the time!

**Comment by glenfant** [comment]
Yes, the error raised even if the ML server is down. Note that you can consider me as some kind of "Python expert", but I'm a real noob in the ML world, and I'll need your help in few ;)

**Comment by paul-hoehne** [comment]
Okay, I think I've fixed the issues with the simple example.
